name = "Hugunica"
license = "AGPLv3"
licenselink = "https://github.com/michaelskyba/hugunica/blob/main/LICENSE"
description = "The Dragon (Hugo) Theme of Hugunica"
min_version = "0.41.0"

[author]
  name = "Michael Skyba"
  homepage = "https://michaelskyba.github.io"
